export enum EActionType {
  SELECT_CONTACT = "SELECT_CONTACT",
  RESET_SELECT_CONTACT = "RESET_SELECT_CONTACT",
  SET_USER = "SET_USER",
  SET_DB_DOCUMENT_REF_ID = "SET_DB_DOCUMENT_REF_ID",
  SET_MESSAGES = "SET_MESSAGES",
  LOAD_CONTACTS = "LOAD_CONTACTS",
  SEND_MESSAGE = "SEND_MESSAGE",
  SET_LOADING = "SET_LOADING",
  SET_THEME = "SET_THEME",
}

export interface IAction {
  type: EActionType;
  payload: any;
}
